{% set name = "pretty_html_table" %}
{% set version = "0.9.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6023ab8db1a48dc0ba4859e158b08f2ddb757752ff226c4546112e8d4f5566bf

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - pandas <=1.2.5
    - python >=3.6

test:
  imports:
    - pretty_html_table

about:
  home: https://github.com/sbi-rviot/ph_table
  license: MIT
  license_family: MIT
  # check to see if PR: https://github.com/sbi-rviot/ph_table/pull/5 has been merged
  # so we can drop the local license in recipe
  license_file: LICENSE.txt
  summary: Make pandas dataframe looking pretty again
  doc_url: ''
  dev_url: https://github.com/sbi-rviot/ph_table

extra:
  recipe-maintainers:
    - Maarten-vd-Sande
